name: Publish to NPM

# Add permissions for the workflow
permissions:
  contents: write
  packages: write

on:
  push:
    tags:
      - "v*" # Triggers on tags like v1.0.0, v1.2.3, etc.

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run type check
        run: npm run type-check

      - name: Build package
        run: npm run build

  publish:
    needs: test
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          registry-url: "https://registry.npmjs.org"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Extract version from tag
        id: version
        run: |
          TAG=${GITHUB_REF#refs/tags/v}
          echo "version=$TAG" >> $GITHUB_OUTPUT
          echo "Publishing version: $TAG"

      - name: Update package version
        run: |
          npm version ${{ steps.version.outputs.version }} --no-git-tag-version

      - name: Build with production config
        run: |
          JUNODECK_API_URL=https://junodeck.com npm run build
        env:
          NODE_ENV: production

      - name: Publish to npm
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: JunoDeck Notebook Renderer v${{ steps.version.outputs.version }}
          body: |
            ## 🚀 JunoDeck Notebook Renderer v${{ steps.version.outputs.version }}

            A React library for rendering Jupyter notebooks with built-in API integration.

            ### 📦 Installation
            ```bash
            npm install @junodeck/notebook-renderer@${{ steps.version.outputs.version }}
            ```

            ### 🔗 Links
            - [📚 API Documentation](./API.md)
            - [📖 README](./README.md)
            - [📦 NPM Package](https://www.npmjs.com/package/@junodeck/notebook-renderer)

            ### 🎨 Features
            - Beautiful notebook rendering
            - Multiple themes (Jupiter Light/Dark, Scientific, Presentation)
            - Built-in API integration
            - TypeScript support
            - Responsive design
          draft: false
          prerelease: ${{ contains(steps.version.outputs.version, '-') }}
